name: Deploy GitHub Pages

on:
  push:
    branches:
      - initial_commit

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Gerar data.js
        run: python generate_data_js.py

      - name: Copiar arquivos para docs/
        run: |
          mkdir -p docs
          cp index.html docs/
          cp docs/data.js docs/

      - name: Commit e push das alterações
        run: |
          # Configurar usuário para o commit
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Adicionar alterações, commitar e empurrar para o repositório
          git add .
          git commit -m "Atualizando pontuação do seletor ${{ steps.issue.outputs.seletorId }}"
          
          # Usar o GITHUB_TOKEN para autenticação no push
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
