name: Deploy GitHub Pages

on:
  push:
    branches:
      - initial_commit

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: pip install -r requirements.txt || true

      - name: Gerar data.js
        run: python generate_data_js.py

      - name: Copiar arquivos para docs/
        run: |
          mkdir -p docs
          cp index.html docs/
          cp docs/data.js docs/

      - name: Commit e push do GitHub Pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git commit -m "Atualizando GitHub Pages com dados de seletores"
          git push
