name: Atualizar Pontuação do Seletor

on:
  issues:
    types: [opened, edited]

jobs:
  atualizar_pontuacao:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Extrair informações do Issue
        id: issue
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            
            // Extrair o seletor ID (corrigido para não usar backticks)
            const seletorIdMatch = issue.body.match(/Identificador do Seletor\s+(.+?)\s+/);
            const seletorId = seletorIdMatch ? seletorIdMatch[1] : null;
            
            // Print para depuração - verificar valor do seletorId
            console.log("Seletor ID extraído: ", seletorId);
            
            // Extrair o tipo de feedback (Positivo ou Negativo)
            const tipoFeedbackMatch = issue.body.match(/Tipo de Feedback\s+- \[x\] Negativo/);
            const tipoFeedback = tipoFeedbackMatch ? 'Negativo' : 'Positivo';
            
            // Definir como saída usando set-output para que outros steps possam acessar
            core.setOutput("seletorId", seletorId);
            core.setOutput("tipoFeedback", tipoFeedback);

      - name: Verificar valores extraídos
        run: |
          echo "Seletor ID: ${{ steps.issue.outputs.seletorId }}"
          echo "Tipo de Feedback: ${{ steps.issue.outputs.tipoFeedback }}"

      - name: Atualizar pontuação
        run: |
          python scripts/update_score.py "${{ steps.issue.outputs.seletorId }}" "${{ steps.issue.outputs.tipoFeedback }}"
      
      - name: Gerar data.js
        run: |
          python scripts/generate_data_js.py

      - name: Commit e push das alterações
        run: |
          # Configurar usuário para o commit
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Adicionar alterações, commitar e empurrar para o repositório
          git add .
          git commit -m "Atualizando pontuação do seletor ${{ steps.issue.outputs.seletorId }}"
          
          # Usar o GITHUB_TOKEN para autenticação no push
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}

